#!/usr/bin/with-contenv bash
# ==============================================================================
# Starts server to serve the app
# ==============================================================================
# shellcheck disable=SC2164
cd /opt/ip-backend

chmod +x /opt/ip-backend/ip-backend

exec /opt/ip-backend/ip-backend
