#!/usr/bin/with-contenv bash
# ==============================================================================
# Starts server to serve the app
# ==============================================================================
# shellcheck disable=SC2164
cd /opt/app

exec /opt/app/ip-backend
